Importando as bibliotecas

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

Carregando DataSet Airliness Delay

In [57]:
#link do Dataset: https://www.kaggle.com/datasets/ulrikthygepedersen/airlines-delay
dados = pd.read_csv('airlines_delay.csv')

#Traduzindo nome das Variáveis
dados.rename({'Flight': 'Voo', 'Time': 'HoraPartida', 'Length': 'Duracao', 'Airline': 'CiaAerea', 'AirportFrom': 'AeroportoOrigem', 'AirportTo': 'AeroportoDestino', 'DayOfWeek': 'DiaDaSemana', 'Class': 'Atrasado'}, axis=1, inplace=True)

Tabela descritiva da variável dependente.

In [58]:
# Tabela descritiva da variável dependente "Atrasado"
tab_descritiva = dados["Atrasado"].value_counts().reset_index()
tab_descritiva.columns = ["Atrasado", "Contagem"]

# Calcular a porcentagem de cada classe
tab_descritiva["Porcentagem"] = (tab_descritiva["Contagem"] / len(dados)) * 100

# Ordenar as classes por ordem decrescente
tab_descritiva = tab_descritiva.sort_values("Atrasado", ascending=False)

# Exibir a tabela descritiva
print("Tabela descritiva da variável dependente 'Atrasado':")
tab_descritiva

Tabela descritiva da variável dependente 'Atrasado':


Atrasado  Contagem  Porcentagem
1         1    240264    44.544312
0         0    299118    55.455688

Transformando os atributos categóricos em numéricos.

In [59]:
# # Lista de variaveis categoricas
cat_cols = dados.select_dtypes(include=['object']).columns.tolist()
cat_cols

['CiaAerea', 'AeroportoOrigem', 'AeroportoDestino']

In [60]:
# Transformando categoricas em numericas
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in cat_cols: 
    le.fit(dados[col])
    dados[col] = le.transform(dados[col])

Definindo o index

In [61]:
dados.set_index("Voo",inplace=True)
dados[['HoraPartida','Duracao']]=MinMaxScaler().fit_transform(dados[['HoraPartida','Duracao']])
dados.head(3)

HoraPartida   Duracao  CiaAerea  AeroportoOrigem  AeroportoDestino  \
Voo                                                                          
2313.0     0.899930  0.215267         5               16               129   
6948.0     0.244927  0.222901        12               65               208   
1247.0     0.811756  0.218321         3               35                60   

        DiaDaSemana  Atrasado  
Voo                            
2313.0            1         0  
6948.0            4         0  
1247.0            3         0

Split 1: Utilizando divisão de 70% para treinamento e 30% para teste

In [62]:
X = dados.drop('Atrasado', axis = 1)
y = dados['Atrasado']

In [63]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

Decision Tree

In [64]:
#Profundidade = 5
modelo111=DecisionTreeClassifier(max_depth=5)
modelo111.fit(X_train,y_train)
y_pred111=modelo111.predict(X_test)

In [65]:
print('Acurácia: ', round(accuracy_score(y_test, y_pred111)*100, 2), '%')

Acurácia:  63.53 %


In [66]:
#Profundidade = 15
modelo112=DecisionTreeClassifier(max_depth=15)
modelo112.fit(X_train,y_train)
y_pred112=modelo112.predict(X_test)

In [67]:
print('Acurácia: ', round(accuracy_score(y_test, y_pred112)*100, 2), '%')

Acurácia:  64.63 %


Random Forest

In [68]:
#Profundidade = 5
modelo121 = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=42, max_depth=5)
modelo121.fit(X_train,y_train)
y_pred121=modelo121.predict(X_test)

In [69]:
print('Acurácia: ', round(accuracy_score(y_test, y_pred121)*100, 2), '%')

Acurácia:  63.13 %


In [70]:
#Profundidade = 15
modelo122 = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=42, max_depth=15)
modelo122.fit(X_train,y_train)
y_pred122=modelo122.predict(X_test)

In [71]:
print('Acurácia: ', round(accuracy_score(y_test, y_pred122)*100, 2), '%')

Acurácia:  65.88 %


 Split 2: Utilizando validação cruzada com k igual a 10.

Decision Tree

In [72]:
#Profundidade = 5
modelo211=DecisionTreeClassifier(max_depth=5)
#gerando modelo
modelo211.fit(X_train, y_train)
#avalia modelo
modelo211.score(X_test, y_test)
#executando validação cruzada com 10 folds
scores1 = cross_val_score(modelo211, X, y, cv=10, scoring='accuracy')
scores1

array([0.63773893, 0.63740522, 0.63628611, 0.63600801, 0.63585969,
       0.63639735, 0.63556305, 0.63715748, 0.64001261, 0.63565575])

In [73]:
#Média dos resultados
print('Acurácia: ', round(scores1.mean()*100, 2), '%')

Acurácia:  63.68 %


In [83]:
#Profundidade = 15
modelo212=DecisionTreeClassifier(max_depth=15)
#gerando modelo
modelo212.fit(X_train, y_train)
#avalia modelo
modelo212.score(X_test, y_test)
#executando validação cruzada com 10 folds
scores1 = cross_val_score(modelo212, X, y, cv=10, scoring='accuracy')
scores1

array([0.65223679, 0.65071655, 0.65232304, 0.65163706, 0.64766955,
       0.65009826, 0.65096963, 0.65163706, 0.65491861, 0.65208202])

In [84]:
#Média dos resultados
print('Acurácia: ', round(scores1.mean()*100, 2), '%')

Acurácia:  65.14 %


Random Forest

In [76]:
#Profundidade = 5
modelo221 = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=42, max_depth=5)
#gerando modelo
modelo221.fit(X_train, y_train)
#avalia modelo
modelo221.score(X_test, y_test)
#executando validação cruzada com 10 folds
scores2 = cross_val_score(modelo221, X, y, cv=10, scoring='accuracy')
scores2

array([0.63278889, 0.63006359, 0.63200341, 0.63357929, 0.63181801,
       0.63187363, 0.63085394, 0.63291186, 0.63374615, 0.63257815])

In [77]:
#Média dos resultados
print('Acurácia: ', round(scores2.mean()*100, 2), '%')

Acurácia:  63.22 %


In [78]:
#Profundidade = 15
modelo222 = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=42, max_depth=15)
#gerando modelo
modelo222.fit(X_train, y_train)
#avalia modelo
modelo222.score(X_test, y_test)
#executando validação cruzada com 10 folds
scores2 = cross_val_score(modelo222, X, y, cv=10, scoring='accuracy')
scores2

array([0.66265596, 0.66258181, 0.66218621, 0.65858949, 0.66036931,
       0.66198228, 0.66198228, 0.66298343, 0.66509696, 0.66235307])

In [79]:
#Média dos resultados
scores2.mean()
print('Acurácia: ', round(scores2.mean()*100, 2), '%')

Acurácia:  66.21 %
